# Generated by Django 4.1.4 on 2023-01-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restoraunt',
            name='city',
            field=models.CharField(default='Нет Данных', max_length=50, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='restoraunt',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название ресторана'),
        ),
    ]
