# Generated by Django 4.1.4 on 2023-01-31 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_restoraunt_city_alter_restoraunt_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restoraunt',
            options={'verbose_name': 'Ресторан', 'verbose_name_plural': 'Рестораны'},
        ),
    ]
