# Generated by Django 4.1.4 on 2022-12-19 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Подкатегория')),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Блюдо')),
                ('compound', models.TextField(blank=True, verbose_name='Состав')),
                ('weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='Выход блюда (граммов)')),
                ('sauce', models.TextField(blank=True, null=True, verbose_name='Соус/Заправка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Красочное описание')),
                ('create_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата редактирования')),
                ('image', models.FileField(blank=True, upload_to='menu_images')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.category', verbose_name='Категория')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.subcategory', verbose_name='Подкатегория')),
            ],
        ),
    ]
