# Generated by Django 4.1.4 on 2023-01-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menuitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Компонент состава')),
            ],
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='compound',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.FileField(blank=True, upload_to='menu_images/', verbose_name='Фото блюда'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='compound',
            field=models.ManyToManyField(to='menu.compound'),
        ),
    ]
