# Generated by Django 4.1.4 on 2023-01-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_compound_remove_menuitem_compound_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='compound',
            field=models.ManyToManyField(related_name='related_compound', to='menu.compound'),
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='sauce',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='sauce',
            field=models.ManyToManyField(related_name='related_sauce', to='menu.compound'),
        ),
    ]
