# Generated by Django 4.1.4 on 2023-01-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_menuitem_compound_remove_menuitem_sauce_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='compound',
            field=models.ManyToManyField(blank=True, related_name='related_compound_compound', to='menu.compound', verbose_name='Состав ингридиента'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Ингридиент'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='compound',
            field=models.ManyToManyField(blank=True, related_name='related_compound', to='menu.compound', verbose_name='Состав блюда'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='sauce',
            field=models.ManyToManyField(blank=True, related_name='related_sauce', to='menu.compound', verbose_name='Состав соуса'),
        ),
    ]
