# Generated by Django 4.1.4 on 2023-01-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_compound_compound_alter_compound_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='compound',
            options={'verbose_name': 'Ингридиент', 'verbose_name_plural': 'Ингридиенты'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Блюдо или напиток', 'verbose_name_plural': 'Блюда и напитки'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название ингридиента'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название подкатегории'),
        ),
    ]
