version: "3.9"
services:

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn puri_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static:/backend/static
      - media:/backend/media
    expose:
      - 8000
    env_file:
      - ./.env

  proj_db:
    image: postgres:13.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      - static:/static
      - media:/media
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend


volumes:
  static:
  media:
  postgres_data: