# Generated by Django 4.1.4 on 2023-02-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_category_options_alter_compound_options_and_more'),
        ('quizes', '0002_alter_answer_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='text',
        ),
        migrations.AddField(
            model_name='answer',
            name='text',
            field=models.ManyToManyField(to='menu.menuitem'),
        ),
    ]
