# Generated by Django 4.1.4 on 2023-02-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_category_options_alter_compound_options_and_more'),
        ('quizes', '0003_remove_answer_text_answer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.ManyToManyField(to='menu.compound'),
        ),
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.ManyToManyField(to='menu.menuitem', verbose_name='Текст вопроса'),
        ),
    ]
